# Generated by Django 5.1.1 on 2024-09-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0003_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='users2',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
