# Generated by Django 5.1.1 on 2024-09-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0005_friends_blocker_friends_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='users2',
            name='language',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
