# Generated by Django 5.1.1 on 2024-09-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0006_users2_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users2',
            name='language',
            field=models.CharField(default='en', max_length=128),
        ),
    ]
