# Generated by Django 5.1.1 on 2024-09-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0007_alter_users2_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users2',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
