# Generated by Django 5.1 on 2024-08-16 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banned',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('banned_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bannee', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
