# Generated by Django 5.0.4 on 2024-05-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=20)),
                ('player2', models.CharField(max_length=20)),
                ('result', models.BooleanField()),
                ('date_of_game', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcendence.games')),
            ],
        ),
    ]
