# Generated by Django 4.2.13 on 2024-06-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='users2',
            name='pictures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transcendence.picture'),
        ),
    ]
