# Generated by Django 4.2.13 on 2024-08-15 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='guest_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
