# Generated by Django 4.2.13 on 2024-06-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0002_picture_users2_pictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='Avatar',
        ),
        migrations.RenameField(
            model_name='users2',
            old_name='pictures',
            new_name='avatar',
        ),
    ]
