# Generated by Django 4.2.13 on 2024-07-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0002_alter_tournaments_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='participants',
            old_name='tournament_id',
            new_name='tournament',
        ),
    ]
