# Generated by Django 4.2.13 on 2024-07-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0003_rename_player_id_participants_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date_of_game',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
