# Generated by Django 5.0.4 on 2024-05-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0003_alter_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='score',
            new_name='losses',
        ),
        migrations.AddField(
            model_name='users',
            name='wins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
