# Generated by Django 4.2.13 on 2024-06-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0004_avatar_name_alter_avatar_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='users2',
            name='avatarDirect',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
