# Generated by Django 4.2.13 on 2024-06-29 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0006_tournaments_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament_Games',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player1_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_games_player1', to=settings.AUTH_USER_MODEL)),
                ('player2_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_games_player2', to=settings.AUTH_USER_MODEL)),
                ('tournament_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transcendence.tournaments')),
            ],
        ),
    ]
